import type { Metadata } from "next";
import "@/styles/globals.css";
import { publicSans } from "@/fonts/fonts.google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          publicSans.className,
          "min-h-screen max-w-screen-2xl mx-auto border overflow-y-auto overflow-x-hidden"
        )}
      >
        {children}
      </body>
    </html>
  );
}
